### ISSUE TITLE
Double mouseenter event causes flickering

### ISSUE THREAD

**Issue by marcingorecki** [urin/jquery.balloon.js#15]
Hi, 

In current (0.6.0) the mouseleave anonymous event is registered twice - lines 174 and 181. This causes a lot of mouseenter events to be generated. This is not visible for simple balloons, but impacts functionality when you put a lot of HTML into it (including lists, graphics and links) as the showBalloon function is called every time mouse is moved inside the balloon. 

Removing 2nd event registration (lines 181-184) does not impact the functionality and removes the problem of multiple 
```
.on("mouseenter", function(e) {
          $balloon.stop(true, true);
          $target.showBalloon();
        })
```

You will need to add .stop in the first event (line 175)

**Comment by urin** [comment]
Could you check [urin/jquery.balloon.js at issue15](https://github.com/urin/jquery.balloon.js/tree/issue15)?
Updated to avoid multiple `.showBalloon()` execution.
If the problem is solved, I will merge this change to master.
