### ISSUE TITLE
tipPosition is not defined

### ISSUE THREAD

**Issue by yakkoroma** [urin/jquery.balloon.js#20]
row 155: ["set" + m.camel.pos.c1](balloon.inner[m.size.c] / tipPosition - len)

i think it should be:
["set" + m.camel.pos.c1](balloon.inner[m.size.c] / options.tipPosition - len)

tipPosition was never defined before, it come out in an error.
At least on Chrome/Linux

**Comment by urin** [comment]
Thank you so much!
