### ISSUE TITLE
Applying delay when using ajax

### ISSUE THREAD

**Issue by femesq** [urin/jquery.balloon.js#22]
Hi,
Thanks for the great project!

I've noticed that even if I set an delay (4000, if I want 4sec), the ajax (JQuery 'load') gets executed on mouse-over, so that delay apply only for "showing" the balloon, not for making fewer connections to the server.

My idea was that using delay, I could make the server request only after 4secs, and that way, the server will not get hit "accidentaly" by the user (only if the user really stays 4sec on mouse over)...

Is there an way to achive this behavior?

Thanks,

**Comment by femesq** [comment]
I'm not a expert JS programmer, but could try to help in this...

What do you think about creating a new parameter (urlDelay) for situations that we don't want to hit the server so often?
Is such case, for example, if we have delay=4000 and urlDelay=3000, if the server response happens in less than 1sec we would have already loaded the dynamic content.

Does it make sense for you?

Thanks,

**Comment by urin** [comment]
I think it is better to add a new option `ajaxContentsMaxAge` to avoid rushing requests.
Once the client gets contents by ajax successfully, it should not request until `ajaxContentsMaxAge` expires. 0 is the same as current behavior. -1 to get once.

**Comment by femesq** [comment]
I understand your suggestion, and the way I was trying to achieve this was creating another option (```urlAlwaysReload: false``` - by default). So, when ```urlAlwaysReload ```is set to ```true```, the behavior would be as it works now.

The idea of setting an ```ajaxContentsMaxAge``` makes total sense, but do not address the situation I'm facing: supposing I have set delay to 4000ms, and want don't want the server to be request unless the users stays "mouse-over" for at least 3000ms.

That's the case because I'm using the plugin to bring details about a list of items I have (and there are around 100's of them). I didn't wanted the server getting hit unintentionally as the user pass the cursor over the items, but only when the cursor stays over for a while (meaning that the users "wants" details on that item).

I've started developing this, but I'm really poorly gifted on JS... :-(
With some patience we can get there...

**Comment by urin** [comment]
Added `ajaxDelay` option now.

**Comment by femesq** [comment]
Thank you very much for this.
I've got an error (using url as a function) and made a pull request. 
There is probably a better solution than mine, but I hope my collaboration helps.

**Comment by urin** [comment]
Please try 444c5c7.
Use `this` in the url function instead of parameters.

**Comment by femesq** [comment]
Yes!
Using ```this``` in my function, instead of the parameter, works great!
Thank you very much!

**Comment by urin** [comment]
Gimme a star! Thanks :grin:
