### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode. 

### ISSUE THREAD

**Issue by onet4** [urin/jquery.balloon.js#25]
Hello, looks like a nice plugin. However, it does not seem to be functioning at all.

I just download the [zip http://www.jqueryscript.net/download/Easy-User-friendly-Tooltip-Plugin-For-jQuery-balloon-js.zipfile]() from [here](http://www.jqueryscript.net/tooltip/Easy-User-friendly-Tooltip-Plugin-For-jQuery-balloon-js.html) and opened the index.html to see the demo.

I don't see a balloon unfortunately.

There is an error in the console.

```
Uncaught SyntaxError: Use of const in strict mode. 
```
I commented out the line in the script source code (`jquery.balloon.js`).

```
'use strict';

```
It resolved the error but I don't see any balloons. 

The downloaded script from the above link was v1.0.0 and I tried v1.0.3 downloaded from GitHub but it has the same issue.

**Comment by urin** [comment]
`use strict` was removed at c948f0c5.
Could you try the latest one?
