### ISSUE TITLE
position bug when you use showBalloon (onclick)

### ISSUE THREAD

**Issue by publicocean0** [urin/jquery.balloon.js#27]
when i click on div i cant show tooltip

for(var i in tools) {
                var tool=tools[i];
                tooldiv.append($('<div class="tool" name="'+i+'">'+tool.icon+'</tool>').on('click',function(){
                $(this).showBalloon();  
                }).showBalloon({html: true, position: 'top',contents:'prova',css: {

  color: "#000000",
  backgroundColor: "#ffffff",
}}));

**Comment by urin** [comment]
Can't understand. Explain again, sorry.

**Comment by publicocean0** [comment]
hi , you can see the problem also in your demo page. 
i m using Chrome Versione 51.0.2704.106 (64-bit).
If you click over pupup dont appear.

**Comment by urin** [comment]
On the demo page, `showBalloon` is executed before contents height is changed by JavaScript at DOMContentLoaded.

Please consider to use `load` event of `window` if the page contains elements that the size are changed   like image without `width` or `height` attribute.

**Comment by publicocean0** [comment]
I m not so precise in the description of problem because it is passed a lot of time and  i passed to use popopver (bootstrap) but also it has a different problem( not function for shift from default centered position and on resize +container=body dont work with fixedposition) , i fixed  it but i might patch bootstrap.they are too much slow to update. Uhmmm maybe i tryed to go back to your plugin ... i will tell you the storytelling :)

**Comment by publicocean0** [comment]
i solved the problem in my project. Sorry the delay but i worked before also in other parts. 
Bootstrap 4 is completetely changed for popover (for my opinion is not the right way to add other dependency). Anyway i added my custom plugin creating a partially new plugin inside my main plugin. In this way i need no dependency. I can close this
