### ISSUE TITLE
Balloon contents changed but on first hover, old contents persist.

### ISSUE THREAD

**Issue by markskayff** [urin/jquery.balloon.js#33]
Hey, congrats for your plugin. I have an issue though. 
How do you update the data within a ballon dynacamically? A method like reset balloon contents, etc... 
Moreover, when I change the balloon contents on the fly doing a new $().balloon() action, then on first mouse hover over the element, the balloon still has the old contents. Do you think you can implement a solution for this?

**Comment by urin** [comment]
You can pass a function to `contents` as an option.
Example:
``` js
$('selector').balloon({
  contents: function() {
    return Math.random();
  }
});
```
It is better to add description about this option.

**Comment by markskayff** [comment]
Hey, using a function with a return statement worked. Not sure why, but thanks. Maybe this should be documented.
