### ISSUE TITLE
Publishing later versions to npm

### ISSUE THREAD

**Issue by jerryjoseph-net** [urin/jquery.balloon.js#38]
I see that jquery-balloon-js 1.0.0 is available in npm. https://www.npmjs.com/package/jquery-balloon-js 

But the latest release seems to be version 1.1.2 which is not available in npm as of now.

Could you publish later versions like 1.0.2 and 1.1.2 to npm?

**Comment by urin** [comment]
Updated [jquery\-balloon\-js](https://www.npmjs.com/package/jquery-balloon-js)

**Comment by jerryjoseph-net** [comment]
Thank you
