### ISSUE TITLE
Don't work reference $(this) in contents (issue like #6)

### ISSUE THREAD

**Issue by dahilu** [urin/jquery.balloon.js#39]
$('.myTable').find('td').each(function(index,value){
            var tempStr = 'Title'+index;
            $(value).attr('title',tempStr);
        });
        $('.myTableTD').balloon({
            position:"right",
            html:true,
            contents:'KKS, которые проверяются:<br>'+$(this).attr('title')            
        });   

Don't show right title $(this).attr('title').  $(this) = document.

**Comment by urin** [comment]
It is not issue of this plugin. Please learn JavaScript itself.
